### ISSUE TITLE
Trying to make an Android Build

### ISSUE THREAD

**Issue by mustafadungar** [soomla/cocos2dx-store-example#12]
Hello,

I have been trying to make an Android build from the cocos2dx-store-example project. Unfortunately with no luck. I have spend more then 2 days now. The app crashes on launch. 

iOS build works fine, without any problems. Could you please check the Android build and let me know if its working at your end?

PS: I am using Cocos2dx 3.1.1 and trying the Soomla Cocos2dx Store v3 branch

![screenshot 2014-06-30 18 33 07](https://cloud.githubusercontent.com/assets/5140673/3438104/bfd79d02-00bf-11e4-9f4c-e64ef6970ccc.png)

**Comment by sluzky** [comment]
@mustafadungar Closing this, re-open if still relevant.
