### ISSUE TITLE
AppDelegate.cpp & cocos2d-x v3.3

### ISSUE THREAD

**Issue by Michael-Hamburger** [soomla/cocos2dx-store-example#17]
In cocos2d-x v3.3beta0 GLView was changed (https://github.com/cocos2d/cocos2d-x/issues/8546).

https://github.com/soomla/cocos2dx-store-example/blob/master/Classes/AppDelegate.cpp#L72

Should be glview = glviewImpl::create("My Game");

**Comment by jonyrock** [comment]
@vedi will you fox this ?

**Comment by sluzky** [comment]
@jonyrock we have it in our pipeline, will update here when we'll work on it.

**Comment by sluzky** [comment]
@Michael-Hamburger @jonyrock fixed now, as of [this](https://github.com/soomla/cocos2dx-store-example/commit/3192e50f21bb62a89d14e789f0fe520c53c80946) commit
