### ISSUE TITLE
CCMarketItem::NONCONSUMABLE not known in latest (4.5.1) cocos2dx-store version

### ISSUE THREAD

**Issue by pepeek** [soomla/cocos2dx-store-example#18]
Your example uses CCMarketItem::NONCONSUMABLE but that is not available  in latest (4.5.1) cocos2dx-store version.
At least I have not found it.
It is only defined in JS version of CCMarketItem but not in C++ version.

Where is the problem then, in this example or in store? Or?
How do I define the non-consumable items?

**Comment by refaelos** [comment]
@pepeek we removed this type of item.

What you should do now is create a LifetimeVG with PurchaseType of PurchaseWithMarket.

**Comment by pepeek** [comment]
Thanks, that helped. I'm ready to close this issue but don't you want to update the example? In the current state it is not even compilable...

**Comment by refaelos** [comment]
yes.

@vedi can you fix the example?
